### ISSUE TITLE
Error parsing the yaml file

### ISSUE THREAD

**Issue by xavidzo** [ccyinlu/multimodal_data_studio#3]
Hello, I keep getting this error when I try to load config .yaml file for the camera_lidar_calibration
```
user selected /root/packages/demo_cam_lidar_calibration
user selected /root/packages/demo_cam_lidar_calibration/camera_lidar_calibration_config.yml
Error using YAML.load (line 53)
Java exception occurred:
unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 1906
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)

Error in YAML.read (line 76)
            X = YAML.load( S );

Error in chessboard_camera_lidar_calibration/init_params_from_config_file (line 362)
            params = YAML.read(params_config_file);

Error in chessboard_camera_lidar_calibration/initParams (line 351)
            init_params_from_config_file(this);

Error in chessboard_camera_lidar_calibration/initInfo (line 466)
            initParams(this);

Error in chessboard_camera_lidar_calibration/init (line 221)
            initInfo(this);

Error in chessboard_camera_lidar_calibration (line 107)
            init(this);

Error in multimodal_data_studio/configDiag/onOk (line 196)
      chessboard_camera_lidar_calibration(current_file_path, data_root, config_file);
 
Error while evaluating DestroyedObject Callback.user selected /root/packages/demo_cam_lidar_calibration
user selected /root/packages/demo_cam_lidar_calibration/camera_lidar_calibration_config.yml
Error using YAML.load (line 53)
Java exception occurred:
unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 1906
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)

Error in YAML.read (line 76)
            X = YAML.load( S );

Error in chessboard_camera_lidar_calibration/init_params_from_config_file (line 362)
            params = YAML.read(params_config_file);

Error in chessboard_camera_lidar_calibration/initParams (line 351)
            init_params_from_config_file(this);

Error in chessboard_camera_lidar_calibration/initInfo (line 466)
            initParams(this);

Error in chessboard_camera_lidar_calibration/init (line 221)
            initInfo(this);

Error in chessboard_camera_lidar_calibration (line 107)
            init(this);

Error in multimodal_data_studio/configDiag/onOk (line 196)
      chessboard_camera_lidar_calibration(current_file_path, data_root, config_file);
 
Error while evaluating DestroyedObject Callback.
```

I am using the sample file you provide for download, this camera_lidar_calibration_config.yaml

```
# configuration file for camera lidar calibration
'chessboardProperties': 7, 9, 0.1085 # square num along y-axis, square num along x-axis, side length of the square in meters
'pointFileType': 'pcd' # type of the point cloud file
'pointcloud_limit': -50, 50, -50, 0, -3, 3 # limitations for the pointcloud, (xmin, xmax, ymin, ymax, zmin, zmax)
'planeFitParams': 0.02, 0, 1, 0, 70 # max distance in meters, reference normal(1x3), max angle in degree
'planeFitParams_stage_1': 0.08, 0, 1, 0, 70 # max distance in meters, reference normal(1x3), max angle in degree
'planeFitParams_stage_2': 0.02, 0, 1, 0, 70 # max distance in meters, reference normal(1x3), max angle in degree
'distanceMat_T': 0.05 # max distance for the distance map, in meters
'ifRemoveGround': 1 # remove the ground, 1 or 0

###############################################################################################################################
# if you choose rangemat method to filter the ground, uncomment the line below
'groundRemoveMethod': 'rangeMat' # now support rangeMat and linefit
'groundScanInd': 12 # horizontal ring id from the top to bottom
'sensorMountAngle': 0 # approximate pitch angle for the lidar sensor in degree
'groundRemovalAngleT': 2 # ground removal angle threshold in degree

###############################################################################################################################
# if you choose linefit method to filter the ground, uncomment the line below
#'groundRemoveMethod': 'linefit' # now support rangeMat and linefit
'linefit_seg_r_min': 0.2
'linefit_seg_r_max': 50
'linefit_seg_n_bins': 360
'linefit_seg_n_segments': 360
'linefit_seg_max_dist_to_line': 0.05
'linefit_seg_max_slope': 0.3
'linefit_seg_max_fit_error': 0.02
'linefit_seg_long_threshold': 1.0
'linefit_seg_max_long_height': 0.1
'linefit_seg_max_start_height': 0.2
'linefit_seg_sensor_height': 2 # the height of the lidar sensor：
'linefit_seg_line_search_angle': 0.1
'linefit_seg_n_threads': 4

'differPointRatio': 2 #

'N_SCAN': 40 # scan line of the lidar
'Horizon_SCAN': 1800 # width for the range image
'segmentTheta': 0.3488 # threshold angle for segmentation in radial
'feasibleSegmentValidPointNum': 30
'segmentValidPointNum': 5
'segmentValidLineNum': 3
'vertical_theta': 7.142,6.141,5.135,4.127,3.114,2.101,1.767,1.421,1.086,0.751,0.406,0.0709,-0.268,-0.606,-0.945,-1.283,-1.621,-1.959,-2.297,-2.636,-2.974,-3.311,-3.647,-3.985,-4.319,-4.660,-4.994,-5.326,-5.667,-5.999,-7.000,-7.997,-8.986,-9.971,-10.947,-11.916,-12.873,-13.825,-14.766,-15.696

'ga_loss_threshold': 500 # ga fitnessLimit for reprojection error
'intrinsic_extrinsic_refine_search_space': 0, 0, 0, 0, 0, 0, 20, 20, 10, 10, 0.1, 0.1 # yaw, pitch, roll, x, y, z, fx, fy, cx, cy, k1, k2
```
Do you know what might be the error?

**Comment by chocoli** [comment]
try `addpath()`

**Comment by xavidzo** [comment]
how should I use `addpath()`?
Can you give more details please @chocoli?

**Comment by chocoli** [comment]
> how should I use `addpath()`?
> Can you give more details please @chocoli?

e.g. /home/cho/multimodal_data_studio-master/multimodal_data_studio.m
Before running multimodal_data_studio.m, add its path in matlab by function `addpath('/home/cho/multimodal_data_studio-master')`

**Comment by xavidzo** [comment]
Hi, I did what you say, but I still get the same error that the 'camera_lidar_calibration_config.yaml' is wrong....
do you any other idea, what could be the problem?

```
>> addpath('/root/multimodal_data_studio')
>> multimodal_data_studio

user selected /root/packages/demo_cam_lidar_calibration
Warning: Name is nonexistent or not a directory: /root/multimodal_data_studio/utils/linefit_ground_segmentation/mex 
> In path (line 109)
  In addpath (line 96)
  In chessboard_camera_lidar_calibration (line 91)
  In multimodal_data_studio/configDiag/onOk (line 196) 
Warning: Directory already exists. 
> In chessboard_camera_lidar_calibration (line 104)
  In multimodal_data_studio/configDiag/onOk (line 196) 
Warning: The following error was caught while executing 'chessboard_camera_lidar_calibration' class destructor:
Dot indexing is not supported for variables of this type.

Error in chessboard_camera_lidar_calibration/delete (line 173)
            if ~isempty(this.guiBrowserTable.handle) && isvalid(this.guiBrowserTable.handle)

Error in chessboard_camera_lidar_calibration (line 75)
        function this = chessboard_camera_lidar_calibration(varargin)

Error in multimodal_data_studio/configDiag/onOk (line 196)
      chessboard_camera_lidar_calibration(current_file_path, data_root, config_file); 
> In chessboard_camera_lidar_calibration (line 75)
  In multimodal_data_studio/configDiag/onOk (line 196) 
Error using YAML.load (line 53)
Java exception occurred:
unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 1920
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)

Error in YAML.read (line 76)
            X = YAML.load( S );

Error in chessboard_camera_lidar_calibration/init_params_from_config_file (line 362)
            params = YAML.read(params_config_file);

Error in chessboard_camera_lidar_calibration/initParams (line 351)
            init_params_from_config_file(this);

Error in chessboard_camera_lidar_calibration/initInfo (line 466)
            initParams(this);

Error in chessboard_camera_lidar_calibration/init (line 221)
            initInfo(this);

Error in chessboard_camera_lidar_calibration (line 107)
            init(this);

Error in multimodal_data_studio/configDiag/onOk (line 196)
      chessboard_camera_lidar_calibration(current_file_path, data_root, config_file);
 
Error while evaluating DestroyedObject Callback.
```

**Comment by chocoli** [comment]
run multimodal_data_studio.m with `pause on errors` mode.
then you can see a variable `S` which starts with a special character. that's the problem.

you can save config.yml in ANSI format or copy all the content into another .yml. then load the new file.
I've tested it on my own windows machine, and it works.

**Comment by xavidzo** [comment]
Hi @chocoli , I tried copying and pasting the content of the config.yml file to a new .yml file, but I still get the same error, unfortunately.
Btw, I am using matlab in Linux / ubuntu 16.04, I don't know if that could be the problem, but it's disappointing

**Comment by chocoli** [comment]
Take it easy, man.
I used 2020b in Linux / ubuntu 20.04. I made a lot of effort to compile because of the relied software versions. I think 16.04 is a good choice since most of the built-in software versions are right.
As I mentioned above,  you should debug the program now.
```
Java exception occurred:
unacceptable character '�' (0xFFFD) special characters are not allowed
Error in YAML.read (line 76)
            X = YAML.load( S );
```
To see what `S` is on your machine, then you can do some test.
Btw, I am in trouble with `invalid mex-file` which has been bothering me for 2 days. It's driving me crazy :(

**Comment by xavidzo** [comment]
I solved it @chocoli. Thank you!
